name: ShopAds2
main: org.hpiz.ShopAds2.ShopAds2
version: 0.35
author: Hpiz
depend:
  - Vault
commands:
  ads:
    description: Control creation and receiving of ad
    usage:
    aliases: ad
  shops:
    description: Actions for current shops
    usage:
    aliases: